server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: https://github.com/ZakariaCHAFI/microservices-config-repo.git